<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="webmate" nsURI="http://cas703.webmate" nsPrefix="cas703.webmate">
  <eClassifiers xsi:type="ecore:EClass" name="HTML">
    <eStructuralFeatures xsi:type="ecore:EReference" name="abbreviation" lowerBound="1"
        upperBound="-1" eType="#//Abbreviation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Abbreviation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ids" upperBound="-1" eType="#//ID"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="symbols" upperBound="-1"
        eType="#//Symbol" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tags" upperBound="-1" eType="#//Tag"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classes" upperBound="-1"
        eType="#//Class" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//Attribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="abbreviation" upperBound="-1"
        eType="#//Abbreviation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="group" upperBound="-1"
        eType="#//Group" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attributeName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attributeValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tagName" eType="#//HTMLTag"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" upperBound="-1"
        eType="#//Attribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="id" eType="#//ID" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="class" upperBound="-1"
        eType="#//Class" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inputString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Class">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="className" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ID">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="HTMLTag">
    <eLiterals name="div"/>
    <eLiterals name="h1" value="1"/>
    <eLiterals name="p" value="2"/>
    <eLiterals name="ul" value="3"/>
    <eLiterals name="li" value="4"/>
    <eLiterals name="a" value="5" literal="a"/>
    <eLiterals name="img" value="6" literal="img"/>
    <eLiterals name="form" value="7" literal="form"/>
    <eLiterals name="input" value="8" literal="input"/>
    <eLiterals name="textarea" value="9" literal="textarea"/>
    <eLiterals name="button" value="10" literal="button"/>
    <eLiterals name="select" value="11" literal="select"/>
    <eLiterals name="option" value="12" literal="option"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Symbol">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tag" eType="#//Tag" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="count" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sym" eType="#//SYM"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Group">
    <eStructuralFeatures xsi:type="ecore:EReference" name="abbreviation" upperBound="-1"
        eType="#//Abbreviation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SYM">
    <eLiterals name="PLUS"/>
    <eLiterals name="MULTIPLY" value="1"/>
    <eLiterals name="GREATER" value="3" literal="GREATER"/>
  </eClassifiers>
</ecore:EPackage>
