/*
 * generated by Xtext 2.30.0
 */
package org.xtext.example.mydsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class WebMateUiModule extends AbstractWebMateUiModule {

	public WebMateUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
