/*
 * generated by Xtext 2.30.0
 */
package org.xtext.example.mydsl1.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.example.webmate.ui.internal.WebmateActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class WebMateExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(WebmateActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		WebmateActivator activator = WebmateActivator.getInstance();
		return activator != null ? activator.getInjector(WebmateActivator.ORG_XTEXT_EXAMPLE_MYDSL1_WEBMATE) : null;
	}

}
