/*
 * generated by Xtext 2.30.0
 */
package org.xtext.example.mydsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class WebMateStandaloneSetup extends WebMateStandaloneSetupGenerated {

	public static void doSetup() {
		new WebMateStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
